---
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: ":bell: automerge"
  color: "8f4fbc"
  description: ""
- name: ":robot: bot"
  color: "69cde9"
  description: ""
- name: ":bug: bug"
  color: "b60205"
  description: ""
- name: ":sparkles: custom enhancement"
  color: "018786"
  description: ""
- name: ":bulb: custom feature"
  color: "03dac6"
- name: ":game_die: dependencies"
  color: "0366d6"
  description: ""
- name: ":memo: documentation"
  color: "c5def5"
  description: ""
- name: ":busts_in_silhouette: duplicate"
  color: "cccccc"
  description: ""
- name: ":speech_balloon: translation"
  color: "b2a8a6"
  description: ""
- name: ":sparkles: enhancement"
  color: "0054ca"
  description: ""
- name: ":bulb: feature"
  color: "0e8a16"
  description: ""
- name: ":mega: feedback"
  color: "03a9f4"
  description: ""
- name: ":rocket: future maybe"
  color: "fef2c0"
  description: ""
- name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: ""
- name: ":pray: help wanted"
  color: "4caf50"
  description: ""
- name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: ""
- name: ":mag: investigate"
  color: "e6625b"
  description: ""
- name: ":thinking: needs more info"
  color: "795548"
  description: ""
- name: ":pushpin: pinned"
  color: "28008e"
  description: ""
- name: ":question: question"
  color: "3f51b5"
  description: ""
- name: ":skull: stale"
  color: "237da0"
  description: ""
- name: ":eyes: upstream"
  color: "fbca04"
  description: ""
- name: ":construction_worker: WIP"
  color: "668000"
  description: ""
- name: ":coffin: wontfix"
  color: "ffffff"
  description: ""
