### Cards ###
generic:
  template: "card_generic"
light:
  template: "card_light"
light_slider:
  template: "card_light_slider"
  variables:
    ulm_card_light_slider_name: "[[[ return variables.name ]]]"
binary_sensor:
  template: "card_binary_sensor"
outlet:
  template: "card_power_outlet"
# thermostat:
# template: card_thermostat
cover_buttons:
  template: "card_cover_with_buttons"
  variables:
    ulm_card_cover_with_buttons_name:
    ulm_card_cover_with_buttons_entity:
graph:
  template: "card_graph"
  variables:
    ulm_card_graph_color: "var(--google-blue)"
    ulm_card_graph_name: "Default name"
    ulm_card_graph_entity: "[[[ return entity.entity_id ]]]"
media:
  template: "card_media_player"
battery:
  template: "card_battery"
  variables:
    ulm_card_battery_attribute: "battery"
media_mini_album:
  template: "card_media_player_with_cover"
media_buttons:
  template: "card_media_player_with_controls"
  variables:
    ulm_card_media_player_with_controls_entity: "[[[ return variables.entity ]]]"
    ulm_card_media_player_with_controls_name: "[[[ return variables.name ]]]"