---
button_card_templates: !include_dir_merge_named "../../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
views:
  - type: "custom:grid-layout"
    title: "home"
    icon: "mdi:home"
    path: "0"
    layout:
      grid-template-columns: "1fr 1fr"
      grid-template-rows: "min-content"
      grid-template-areas: |
        "main popup"
      mediaquery:
        "(max-width: 1100px), (orientation: portrait)":
          grid-template-columns: "100%"
          grid-template-areas: "main"
    cards:
      - !include "views/main.yaml"
      - !include "popup/popup.yaml"

  - type: "custom:grid-layout"
    title: "Livingroom"
    icon: "mdi:sofa"
    path: "Livingroom"
    layout:
      grid-template-columns: "1fr 1fr"
      grid-template-rows: "min-content"
      grid-template-areas: |
        "livingroom popup"
      mediaquery:
        "(max-width: 1100px), (orientation: portrait)":
          grid-template-columns: "100%"
          grid-template-areas: "livingroom"
    cards:
      - !include "views/livingroom.yaml"
      - !include "popup/popup.yaml"
