### Vertical Buttons Green ###
vertical_buttons_green:
  variables:
    state: "default"
  template: 
    - vertical_buttons
  state:
    - operator: template
      value: "[[[ return states['input_select.localisation_thomas'].state == variables.state ]]]"
      styles:
        icon:
          - color: 'rgba(var(--color-green),1)'
        label:
          - color: 'rgba(var(--color-green-text),1)'
        name:
          - color: 'rgba(var(--color-green-text),1)'
        img_cell:
          - background-color: 'rgba(var(--color-green), 0.2)'
        card:
          - background-color: 'rgba(var(--color-background-green), var(--opacity-bg))'