---
custom_card_settings_notification_chip:
  type: "custom:button-card"
  icon: "[[[ return variables.ulm_custom_card_settings_notification_chip_icon; ]]]"
  show_icon: true
  styles:
    card:
      - border-radius: "18px"
      - height: "36px"
      - width: "36px"
      - padding-left: "6px"
      - padding-right: "6px"
    custom_fields:
      notification:
        - border-radius: "50%"
        - position: "absolute"
        - left: "65%"
        - top: "15%"
        - height: "6px"
        - width: "6px"
        - animation: >
            [[[ 
              if (states['update.home_assistant_core_update'].state == 'on') return 'flasher 1s infinite';
              if (states['update.home_assistant_operating_system_update'].state == 'on') return 'flasher 1s infinite';
              if (states['update.home_assistant_supervisor_update'].state == 'on') return 'flasher 1s infinite';
            ]]]
  size: "80%"
  custom_fields:
    notification: "none"
  extra_styles: >
    @keyframes flasher {
              100% {background-color: #FF7121
              } 
  tap_action:
    action: "navigate"
    navigation_path: "/config/dashboard/"
