---
ui_lovelace_minimalist: !include "../../custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml"
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: var(--background-image)
views: !include_dir_merge_list views/
