ulm_language_variables:
  variables:
    ulm_on: "on"
    ulm_off: "off"
    ulm_open: "open"
    ulm_closed: "closed"
    ulm_unavailable: "unavailable"
    ulm_standby: "standby"
    ulm_idle: "idle"
    ulm_currency: "$"
    ulm_popups_back: "Back"
    ulm_popups_toggle: "Toogle"
    ulm_popups_statistics: "Statistics"