#!/usr/bin/env python3

import logging

import requests

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

cards = (
    (
        "button-card",
        "https://github.com/custom-cards/button-card/releases/download/v7.0.1/button-card.js",
    ),
    (
        "light-entity-card",
        "https://github.com/ljmerza/light-entity-card/releases/download/6.1.3/light-entity-card.js",
    ),
    (
        "lovelace-auto-entities",
        "https://raw.githubusercontent.com/thomasloven/lovelace-auto-entities/v1.16.1/auto-entities.js",
    ),
    # card-mod: https://github.com/thomasloven/lovelace-card-mod/tree/3.1.2#performance-improvements
    (
        "lovelace-card-mod",
        "https://raw.githubusercontent.com/thomasloven/lovelace-card-mod/v4.1.0/card-mod.js",
    ),
    (
        "mini-graph-card",
        "https://github.com/kalkih/mini-graph-card/releases/download/v0.13.0/mini-graph-card-bundle.js",
    ),
    (
        "mini-media-player",
        "https://github.com/kalkih/mini-media-player/releases/download/v1.16.10/mini-media-player-bundle.js",
    ),
    (
        "my-cards",
        "https://github.com/AnthonMS/my-cards/releases/download/v1.0.6/my-cards.js",
    ),
    (
        "simple-weather-card",
        "https://github.com/kalkih/simple-weather-card/releases/download/v0.8.5/simple-weather-card-bundle.js",
    ),
    (
        "weather-radar-card",
        "https://github.com/Makin-Things/weather-radar-card/releases/download/v2.1.1/weather-radar-card.js",
    ),
    # for adaptive dashboard
    (
        "lovelace-layout-card",
        "https://raw.githubusercontent.com/thomasloven/lovelace-layout-card/v2.4.7/layout-card.js",
    ),
    (
        "lovelace-state-switch",
        "https://raw.githubusercontent.com/thomasloven/lovelace-state-switch/1.9.6/state-switch.js",
    ),
)

for card, src in cards:
    logger.info("Fetching card: %s",card)
    try:
        r = requests.get(src, allow_redirects=True)
        r.raise_for_status()

        open(
            f"custom_components/ui_lovelace_minimalist/cards/{card}/{card}.js", "wb"
        ).write(r.content)
    except Exception as err:
        logger.exception("ERROR: %s", err)
        exit(1)
