---
name: "Add contributors"
on:
  push:
    # Should only run on "dev" due push protected main branch
    branches: ["dev"]

jobs:
  add-contributors:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "BobAnkh/add-contributors@master"
        with:
          CONTRIBUTOR: "### Contributors"
          COLUMN_PER_ROW: "6"
          IMG_WIDTH: "30"
          FONT_SIZE: "10"
          AVATAR_SHAPE: "round"
          PATH: "/README.md"
          BRANCH: "dev"
          COMMIT_MESSAGE: "docs(README): update contributors"
          ACCESS_TOKEN: "${{secrets.GITHUB_TOKEN}}"
