---
name: "Pages test"

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  pages-test:
    name: "Pages test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: "actions/checkout@v2"
      - name: "⚙️ Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - run: "pip install mkdocs-material mkdocs-macros-plugin mkdocs-awesome-pages-plugin"
      - run: "mkdocs build --strict"
